### ISSUE TITLE
glyphname = kstroke.sc.001;

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#22]
This looks like it should be named `kstroke.sc`
and included in OpenType code for Small Caps (smcp) ... and (c2sc).

To be sure, I checked and that is what it says on line 386750 of the `Junicode-width.glyphs` file.
`glyphname = kstroke.sc.001;`
And it does not appear to be included in the `smcp` or `c2cp` OpenType features under either name.

**Comment by psb1558** [comment]
An oops. I have fixed it.

**Comment by kenmcd** [comment]
OK. I see the name change to `kstroke.sc`, 
but I still do not see it included in  either `c2sc` or `smcp`.
Is that intended?

**Comment by psb1558** [comment]
Since this is one of the areas where I let Glyphs automate, I tend to update smcp and c2sc just before I generate new fonts. They're fixed now.

**Comment by kenmcd** [comment]
Yes, I realized this is probably a part of an automated process.
Looks good now!
