### ISSUE TITLE
RightToLeftMirroredForms - incorrect glyph & name

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#8]
In RightToLeftMirroredForms (rtlm) one glyph has the wrong name and the wrong glyph.
`fehufeohfef-runr.001` should be `fehufeohfef-runr.rtl`
And it should be the flipped glyph.
![fehufeohfef-runr 001](https://user-images.githubusercontent.com/844920/82722063-fe513e80-9c77-11ea-80ba-5951c032cfdb.png)

Nice work on all the upgrades so far ! ! !

**Comment by psb1558** [comment]
Good catch--thanks!
I have fixed it.

**Comment by psb1558** [comment]
Closing this now.

**Comment by kenmcd** [comment]
I see the glyph has been changed to the correct flipped glyph, but 
the glyph name still appears to be wrong.
`fehufeohfef-runr.001` should be `fehufeohfef-runr.rtl`
to match the rest of the mirrored glyphs.
The RightToLeftMirroredForms (rtlm) now works properly, but
if you are searching for all `".rtl"` glyphs it will not show-up.

**Comment by psb1558** [comment]
I didn't understand that part at first because you're using an app that renames the glyphs (the names in the Glyphs file are Feoh and Feoh.rtl). But I see now that the production name that should have been uni16A0.rtl was instead uni16A0.001. I have changed this.

**Comment by kenmcd** [comment]
Ahhh ... I see.
I was looking at the `rtlm` in FontCreator OpenType designer.
And did not realize it had renamed the glyphs.
There is an option on open to _Generate friendly glyph names_ - which I have now turned-off.
Hopefully that will prevent me from creating more confusion in the future.
Now when I open that previous version I see the `uni16A0.001` .
Glad it finally made sense and you got it fixed.

**Comment by psb1558** [comment]
Well, friendly names are nice to work with, and then when you generate a font it should default to the (incomprehensible) production names again.
